/**
 * Casual-player model (spec 17.1): N short sessions per day, the rest is offline (50% rate, 8 h cap per return).
 * Each session: claim offline earnings, then play `sessionMin` minutes with the balance bot.
 * usage: tsx scripts/casual.ts [sessionMinutes]
 */
import { writeFileSync } from 'node:fs';
import { newGame, estimateIncomePerSecond, claimOffline } from '../src/core/game';
import { runBot, isMaxed } from '../src/core/bot';
import { OFFLINE } from '../src/config/balance';

const sessionMin = Number(process.argv[2] ?? 5);
console.log(`casual model: ${sessionMin} min sessions, offline ${OFFLINE.rate * 100}% capped at ${OFFLINE.maxHours} h`);
console.log('sessions/day | days to everything maxed | active play (h)');
const rows: string[] = [];
for (const perDay of [1, 2, 3, 5, 8]) {
  const s = newGame(1);
  const gapH = 24 / perDay;
  let days = 0, active = 0;
  for (let i = 0; i < 100000 && !isMaxed(s); i++) {
    // return: offline earnings for the gap (income at the moment the player left, estimate stands in for the EMA)
    if (i > 0) {
      s.incomeEma = estimateIncomePerSecond(s);
      s.lastSeen = 0;
      s.rt.offline = s.incomeEma * OFFLINE.rate * Math.min(gapH, OFFLINE.maxHours) * 3600;
      claimOffline(s, false);
      days += gapH / 24;
    }
    runBot(s, { mode: 'fast', maxSeconds: sessionMin * 60, until: isMaxed });
    active += sessionMin / 60;
    // the game keeps running only while the app is open: no income during the gap except the offline claim above
  }
  console.log(`${String(perDay).padStart(12)} | ${days.toFixed(1).padStart(24)} | ${active.toFixed(1)}`);
  rows.push(`| ${perDay} | every ${gapH.toFixed(1)} h | ${days.toFixed(1)} days | ${active.toFixed(1)} h |`);
}
if (process.argv.includes('--write')) {
  writeFileSync(new URL('../docs/casual-play.md', import.meta.url), `# Casual play model\n\nGenerated by \`npx tsx scripts/casual.ts ${sessionMin} --write\`. Spec target (docs/concept.md 17.1): a casual player with a few short sessions per day and offline earnings reaches the end of Season 1 in about 7 to 12 days.\n\nModel: each session lasts ${sessionMin} minutes of optimal play (balance bot), the player is away the rest of the day; on return the offline dialog pays ${OFFLINE.rate * 100}% of income for the time away, capped at ${OFFLINE.maxHours} h (no ad doubling assumed; doubling would shorten this).\n\n| Sessions per day | Gap between sessions | Days to everything maxed | Total active play |\n|---|---|---|---|\n${rows.join('\n')}\n\nReading: 2 to 3 sessions a day lands at 6 to 10 days, inside the target. One session a day is slow because the 8 h cap wastes most of a 24 h gap; 5 to 8 sessions a day approaches the pure active-play time. Offline doubling by rewarded ad and the ski bus are not modelled, so real players should be a little faster.\n`);
  console.log('wrote docs/casual-play.md');
}
