/** Prints (and writes to docs/design-tables.md) the design tables derived from src/config: lifts, costs, capacity, income ceilings. */
import { writeFileSync } from 'node:fs';
import { LIFT_TIERS, LEVEL_MAX } from '../src/config/lifts';
import { AREAS } from '../src/config/areas';
import { BUILDINGS } from '../src/config/facilities';
import { ZONES } from '../src/config/zones';
import { PARKING, HOUSING } from '../src/config/capacity';
import { throughput, ticketPrice, levelUpgradeCost, tierBuildCost, areaCost, slotCost, parkingCost, housingCost, parkingCapacityAt, housingCapacityAt, buildingCost, zoneBuyCost } from '../src/core/game';
import { formatMoney } from '../src/ui/format';

const f = (n: number) => formatMoney(n);
const rows: string[] = [];
rows.push('# Design tables\n\nGenerated by `npx tsx scripts/design-tables.ts` from `src/config/*` (costs include the tuned `TUNE` multipliers).\n');

rows.push('## Lift tiers\n\n| Tier | Name | People/ride | Interval | Ride | Price | Saturated income (base) | Saturated income (level 10) | Tier cost | Level 0 to 10 cost |\n|---|---|---|---|---|---|---|---|---|---|');
for (const t of LIFT_TIERS) {
  const base = throughput({ tier: t.tier, level: 0 }) * ticketPrice({ tier: t.tier, level: 0 });
  const max = throughput({ tier: t.tier, level: LEVEL_MAX }) * ticketPrice({ tier: t.tier, level: LEVEL_MAX });
  let lv = 0; for (let L = 0; L < LEVEL_MAX; L++) lv += levelUpgradeCost(t.tier, L);
  rows.push(`| ${t.tier} | ${t.name} | ${t.capacity} | ${t.interval}s | ${t.rideBase}s | ${f(t.price)} | ${f(base)}/s | ${f(max)}/s | ${f(tierBuildCost(t.tier))} | ${f(lv)} |`);
}
rows.push('\nDesign invariant: the base saturated income of tier t+1 is at least the level-10 saturated income of tier t.\n');

rows.push('## Areas\n\n| Area | Price | Lift slots (slot fee) | Ski time | Unlocks |\n|---|---|---|---|---|');
for (const a of AREAS) rows.push(`| ${a.name} | ${f(areaCost(a.id))} | ${a.slots.map((_, i) => f(slotCost(a.id, i))).join(', ')} | ${a.skiTime}s | ${a.unlocks} |`);

rows.push('\n## Population\n\n| Level | Parking capacity | Parking cost (to next) | Housing capacity | Housing cost (to next) |\n|---|---|---|---|---|');
for (const L of [0, 1, 2, 5, 10, 15, 20, 25, 29]) {
  rows.push(`| ${L} | ${parkingCapacityAt(L)} | ${f(parkingCost(L))} | ${L <= HOUSING.levelMax ? housingCapacityAt(L) : '-'} | ${L < HOUSING.levelMax ? f(housingCost(L)) : '-'} |`);
}
rows.push(`\nParking max ${PARKING.levelMax} levels = ${parkingCapacityAt(PARKING.levelMax)} spaces, housing max ${HOUSING.levelMax} levels = ${housingCapacityAt(HOUSING.levelMax)} beds, ski bus +40, hard cap 200.\n`);

rows.push('## Buildings and zones\n\n| Item | Needs | Price | Notes |\n|---|---|---|---|');
for (const b of BUILDINGS) rows.push(`| ${b.name} | ${b.requiresArea} | ${f(buildingCost(b.id))} | ${b.baseIncome}/s base${b.lodgeBonus ? `, lodge bonus ${b.lodgeBonus}` : ''} |`);
for (const z of ZONES) rows.push(`| ${z.name} | ${z.requiresArea} | ${f(zoneBuyCost(z.id, 0))}${z.stages ? ` (stages ${z.stages.map((_, i) => f(zoneBuyCost(z.id, i))).join(' / ')})` : ''} | fee ${z.stages ? z.stages.map(s => s.fee).join('/') : z.fee}, fits ${z.stages ? z.stages.map(s => s.capacity).join('/') : z.capacity}, stay ${z.stay}s |`);

const md = rows.join('\n') + '\n';
writeFileSync(new URL('../docs/design-tables.md', import.meta.url), md);
console.log(md);
