import { writeFileSync } from 'node:fs';
import { newGame } from '../src/core/game';
import { runBot, MILESTONES, BOT } from '../src/core/bot';
import { TUNE } from '../src/config/balance';

const args = process.argv.slice(2);
const mode = args.includes('--full') ? 'full' : 'fast';
const minutes = Number((args.find(a => a.startsWith('--minutes='))?.split('=')[1]) ?? (mode === 'full' ? 30 : 0));
const fmt = (sec: number) => {
  if (sec < 120) return `${sec.toFixed(0)}s`;
  if (sec < 7200) return `${(sec / 60).toFixed(1)}m`;
  return `${(sec / 3600).toFixed(2)}h`;
};

const tuneArg = args.find(a => a.startsWith('--tune='));
if (tuneArg) Object.assign(TUNE, JSON.parse(tuneArg.slice(7)));
const botArg = args.find(a => a.startsWith('--areabonus='));
if (botArg) BOT.areaBonus = botArg.split('=')[1].split(',').map(Number);
const s = newGame(1);
const t0 = Date.now();
const res = runBot(s, { mode, maxSeconds: minutes > 0 ? minutes * 60 : undefined });
console.log(`mode=${mode} simulated=${fmt(res.time)} purchases=${res.purchases} maxed=${res.finished} wall=${((Date.now() - t0) / 1000).toFixed(1)}s`);
console.log('TUNE', JSON.stringify(TUNE));
console.log('milestone'.padEnd(26), 'target'.padEnd(9), 'actual'.padEnd(9), 'dev');
for (const m of MILESTONES) {
  const at = res.timeline[m.id];
  const dev = at === undefined ? 'n/a' : `${(((at - m.target) / m.target) * 100).toFixed(0)}%`;
  console.log(m.label.padEnd(26), fmt(m.target).padEnd(9), (at === undefined ? '-' : fmt(at)).padEnd(9), dev);
}
console.log('income checkpoints:', res.checkpoints.slice(0, 12).map(c => `${fmt(c.t)}:$${c.income.toFixed(1)}/s`).join('  '));
console.log('angry leaves:', res.angryLeaves);

if (args.includes('--report')) {
  const rows = MILESTONES.map(m => {
    const at = res.timeline[m.id];
    const dev = at === undefined ? 'n/a' : `${(((at - m.target) / m.target) * 100).toFixed(0)}%`;
    const tol = m.id === 'firstUpgrade' ? '-' : `${((m.tol ?? 0.35) * 100).toFixed(0)}%`;
    const ok = at === undefined ? 'no' : m.id === 'firstUpgrade' ? (at <= m.target ? 'yes' : 'no') : Math.abs(at / m.target - 1) <= (m.tol ?? 0.35) ? 'yes' : 'no';
    return `| ${m.label} | ${fmt(m.target)} | ${at === undefined ? '-' : fmt(at)} | ${dev} | ${tol} | ${ok} |`;
  });
  const cps = res.checkpoints.slice(0, 14).map(c => `| ${fmt(c.t)} | $${c.income.toFixed(1)}/s |`);
  const md = `# Balance report

Generated by \`npm run simulate -- --fast --report\` (balance bot, analytic mode, optimal payback play, no offline).

Total time to everything maxed: **${fmt(res.time)}** with ${res.purchases} purchases.

## Tuned cost multipliers (\`TUNE\` in \`src/config/balance.ts\`)

\`\`\`json
${JSON.stringify(TUNE, null, 1)}
\`\`\`

## Milestones (actual vs target)

| Milestone | Target | Actual | Deviation | Tolerance | In tolerance |
|---|---|---|---|---|---|
${rows.join('\n')}

## Income checkpoints (estimated income per second)

| Time | Income |
|---|---|
${cps.join('\n')}

## Notes

- The bot is a greedy payback optimiser. Its purchase order is emergent, so some milestones flip discontinuously when a cost crosses a threshold (Lower Slopes and Mid Mountain in particular): tuning a single cost cannot place both exactly at target. Ordering after the first chair is bot-driven, a human will usually buy areas earlier than the bot does.
- The analytic estimate was cross-checked against the real simulation on 5 hand-built states (tests/core.test.ts, all within 25%; actual 0.85 to 1.18 ratio).
- Full-simulation mode (\`--full\`) reproduces the first 30 minutes of the fast timeline within about 15 to 25 percent.
- The gap between the two notable outliers and the late-game length is documented in docs/decisions.md.
`;
  writeFileSync(new URL('../docs/balance-report.md', import.meta.url), md);
  console.log('wrote docs/balance-report.md');
}
